version: '3'

services:

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   env_file: .env
  #   environment: 
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
  #     - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
  #     - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
  #   volumes:
  #     - ${PWD}/_data/mongo:/data/db
  #     - ${PWD}/docker/_mongo/fixtures:/import
  #     - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
  #   ports:
  #     - 27017:27017

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}      
    ports:
      - 5432:5432
    networks:
      - tmapi_default
    volumes:
      - ${PWD}/_data/postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:6
  #   container_name: redis
  #   restart: always
  #   env_file: .env
  #   command: redis-server --requirepass $REDIS_PASSWORD
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ${PWD}/_data/redis:/var/lib/redis

  tmapi:
    build: ./tmapi
    image: tmapi:latest
    container_name: tmapi
    restart: always
    # command: "python manage.py runserver 0.0.0.0:8000"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:      
      - ${PWD}/:/tmapi
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - tmapi_default  # Add this line to connect to the network
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=tm.settings

  # celery:
  #   build: ./trailerMais
  #   image: trailerMais:latest
  #   container_name: celery
  #   restart: always
  #   command: [
  #     "celery",
  #     "-A",
  #     "trailerMais",
  #     "worker",
  #     "-c",
  #     "1",
  #     "-l",
  #     "INFO",
  #     "--without-heartbeat",
  #     "--without-gossip",
  #     "--without-mingle",
  #   ]
  #   env_file: .env
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=trailerMais.settings
  #     - DJANGO_WSGI=trailerMais.wsgi
  #     - DEBUG=True
  #   volumes:
  #     - ${PWD}/trailerMaisAPI:/trailerMaisAPI
  #   depends_on:
  #     - postgres
  #     - redis

networks:
  tmapi_default:  # Define the network
    external: true